on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-typescript-package:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: install
        run: npm install
      - name: generate and publish
        run: ./gen-typescript.sh prerelease
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  generate-swift-package:
    runs-on: ubuntu-latest
    if: "github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/generate-native-package
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          platform: "ios"
          release_type: "prerelease"

  generate-android-package:
    needs: bump-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/generate-native-package
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          platform: "android"
