on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Version from latest tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo $VERSION
          echo "version=$VERSION\n" >> $GITHUB_OUTPUT

  generate-typescript-package:
    needs: version
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: install
        run: npm install

      - name: generate and publish
        run: ./gen-typescript.sh prerelease ${VERSION}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ needs.version.outputs.version }}

  # generate-swift-package:
  #   needs: version
  #   runs-on: ubuntu-latest
  #   if: "github.event.release.prerelease"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/generate-native-package
  #       with:
  #         access_token: ${{ secrets.ACCESS_TOKEN }}
  #         platform: "ios"
  #         release_type: "prerelease"
  #         version: ${{ needs.version.outputs.version }}

  # generate-android-package:
  #   needs: version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/generate-native-package
  #       with:
  #         access_token: ${{ secrets.ACCESS_TOKEN }}
  #         platform: "android"
  #         release_type: "prerelease"
  #         version: ${{ needs.version.outputs.version }}
