on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "thrift/**"

permissions:
  contents: read

jobs:
  validate-thrift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: ./.github/actions/validate-thrift
