on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-thrift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/validate-thrift
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.head_ref }}
